#web
quarkus.application.name=centerstage
quarkus.http.port=50700
quarkus.http.io-threads=10

#monitoring
quarkus.smallrye-health.root-path=/actuator/health
quarkus.smallrye-health.liveness-path=/actuator/health/liveness
quarkus.smallrye-health.readiness-path=/actuator/health/readiness
quarkus.micrometer.export.prometheus.path=/actuator/prometheus

#openapi
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.store-schema-directory=doc/generated

#tracing
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.log.category."io.opentelemetry.exporter.internal".level=OFF
quarkus.log.category."io.quarkus.opentelemetry.runtime.exporter.otlp.sender".level=OFF

#logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.level=INFO
quarkus.log.category."org.goafabric".level=INFO

#jacoco
quarkus.jacoco.report=false

#centerstage
#centerstage.catalog.file=doc/catalog/entities-local.yaml
centerstage.catalog.file=https://github.com/goafabric/backstage/blob/develop/catalog/entities-git.yaml

techradar.url=https://github.com/goafabric/example-konstruction-kit/blob/develop/helm/infra/techradar/data/config-backstage.json

#github
quarkus.rest-client.GitHubAdapter.url=https://api.github.com
quarkus.rest-client.GitHubAdapter.connect-timeout=10000
quarkus.rest-client.GitHubAdapter.read-timeout=10000

#gitlab
quarkus.rest-client.GitLabAdapter.url=https://gitlab.com
quarkus.rest-client.GitLabAdapter.connect-timeout=10000
quarkus.rest-client.GitLabAdapter.read-timeout=10000
#gitlab.token=<your-token-here>
# Alternatively set the GITLAB_TOKEN environment variable

